# Generated by Django 4.0 on 2022-01-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(blank=True, max_length=300, null=True, verbose_name='Marque')),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('titre', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('prix', models.FloatField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('date_pub', models.DateTimeField(null=True, verbose_name='Date  de publication')),
            ],
        ),
    ]
